name: Deploy to GitHub Pages
on:
  push:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install dependencies
      run: npm i
    - name: Build and deploy to GitHub Pages
      run: |
        git config --local user.name "GitHub Pages Publisher"
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"
        npx gulp deploy
